# Configurations
DATASET_NAME = "malaria"
BATCH_SIZE = 32
TRAIN_SPLIT = "train[:70%]"
VAL_SPLIT = "train[70%:85%]"
TEST_SPLIT = "train[85%:]"
SHUFFLE_BUFFER_MULTIPLIER = 16
IMAGE_SIZE = (224, 224)
EPOCHS = 10
TOP_DROPOUT_RATE = 0.2
START_LR = 0.05
TARGET_LR = 1e-2
WEIGHT_DECAY = 5e-4
MOMENTUM = 0.9
PATIENCE = 2
LABEL_SMOOTHING = 0.1
NUM_CLASSES = 2
